# Generated by Django 3.1.3 on 2020-11-23 12:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('onlineshop', '0002_adress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adress',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='endpoint', to='onlineshop.order'),
        ),
    ]
