# Generated by Django 3.1.3 on 2020-11-24 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('onlineshop', '0003_auto_20201123_1201'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='products',
        ),
    ]
